// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// horizon_svf_opns
List horizon_svf_opns(NumericMatrix padded, int pad, int nrow_out, int ncol_out, IntegerVector dx, IntegerVector dy, NumericVector dist, IntegerVector dir_start, IntegerVector dir_end, bool want_svf, bool want_opns, int threads);
RcppExport SEXP _rvtr_horizon_svf_opns(SEXP paddedSEXP, SEXP padSEXP, SEXP nrow_outSEXP, SEXP ncol_outSEXP, SEXP dxSEXP, SEXP dySEXP, SEXP distSEXP, SEXP dir_startSEXP, SEXP dir_endSEXP, SEXP want_svfSEXP, SEXP want_opnsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type padded(paddedSEXP);
    Rcpp::traits::input_parameter< int >::type pad(padSEXP);
    Rcpp::traits::input_parameter< int >::type nrow_out(nrow_outSEXP);
    Rcpp::traits::input_parameter< int >::type ncol_out(ncol_outSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dy(dySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dir_start(dir_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dir_end(dir_endSEXP);
    Rcpp::traits::input_parameter< bool >::type want_svf(want_svfSEXP);
    Rcpp::traits::input_parameter< bool >::type want_opns(want_opnsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(horizon_svf_opns(padded, pad, nrow_out, ncol_out, dx, dy, dist, dir_start, dir_end, want_svf, want_opns, threads));
    return rcpp_result_gen;
END_RCPP
}
// slope_hillshade
List slope_hillshade(NumericMatrix padded, int pad, int nrow_out, int ncol_out, double xres, double yres, double sun_azimuth, NumericVector sun_elevations, int threads);
RcppExport SEXP _rvtr_slope_hillshade(SEXP paddedSEXP, SEXP padSEXP, SEXP nrow_outSEXP, SEXP ncol_outSEXP, SEXP xresSEXP, SEXP yresSEXP, SEXP sun_azimuthSEXP, SEXP sun_elevationsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type padded(paddedSEXP);
    Rcpp::traits::input_parameter< int >::type pad(padSEXP);
    Rcpp::traits::input_parameter< int >::type nrow_out(nrow_outSEXP);
    Rcpp::traits::input_parameter< int >::type ncol_out(ncol_outSEXP);
    Rcpp::traits::input_parameter< double >::type xres(xresSEXP);
    Rcpp::traits::input_parameter< double >::type yres(yresSEXP);
    Rcpp::traits::input_parameter< double >::type sun_azimuth(sun_azimuthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sun_elevations(sun_elevationsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(slope_hillshade(padded, pad, nrow_out, ncol_out, xres, yres, sun_azimuth, sun_elevations, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rvtr_horizon_svf_opns", (DL_FUNC) &_rvtr_horizon_svf_opns, 12},
    {"_rvtr_slope_hillshade", (DL_FUNC) &_rvtr_slope_hillshade, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_rvtr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
