# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

horizon_svf_opns <- function(padded, pad, nrow_out, ncol_out, dx, dy, dist, dir_start, dir_end, want_svf, want_opns, want_asvf, dir_weight, threads) {
    .Call(`_rvtr_horizon_svf_opns`, padded, pad, nrow_out, ncol_out, dx, dy, dist, dir_start, dir_end, want_svf, want_opns, want_asvf, dir_weight, threads)
}

slope_hillshade <- function(padded, pad, nrow_out, ncol_out, xres, yres, sun_azimuths, sun_elevations, threads) {
    .Call(`_rvtr_slope_hillshade`, padded, pad, nrow_out, ncol_out, xres, yres, sun_azimuths, sun_elevations, threads)
}

local_dominance_kernel <- function(padded, pad, nrow_out, ncol_out, dx, dy, dist, weight, observer_height, threads) {
    .Call(`_rvtr_local_dominance_kernel`, padded, pad, nrow_out, ncol_out, dx, dy, dist, weight, observer_height, threads)
}

msrm_kernel <- function(padded, pad, nrow_out, ncol_out, radii, threads) {
    .Call(`_rvtr_msrm_kernel`, padded, pad, nrow_out, ncol_out, radii, threads)
}

max_deviation_kernel <- function(padded, pad, nrow_out, ncol_out, r_min, r_max, r_step, threads) {
    .Call(`_rvtr_max_deviation_kernel`, padded, pad, nrow_out, ncol_out, r_min, r_max, r_step, threads)
}

sky_illumination_kernel <- function(padded, pad, nrow_out, ncol_out, xres, yres, dx, dy, dist, dir_start, dir_end, dir_azimuth, overcast, threads) {
    .Call(`_rvtr_sky_illumination_kernel`, padded, pad, nrow_out, ncol_out, xres, yres, dx, dy, dist, dir_start, dir_end, dir_azimuth, overcast, threads)
}

