# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

horizon_svf_opns <- function(padded, pad, nrow_out, ncol_out, dx, dy, dist, dir_start, dir_end, want_svf, want_opns, threads) {
    .Call(`_rvtr_horizon_svf_opns`, padded, pad, nrow_out, ncol_out, dx, dy, dist, dir_start, dir_end, want_svf, want_opns, threads)
}

slope_hillshade <- function(padded, pad, nrow_out, ncol_out, xres, yres, sun_azimuth, sun_elevations, threads) {
    .Call(`_rvtr_slope_hillshade`, padded, pad, nrow_out, ncol_out, xres, yres, sun_azimuth, sun_elevations, threads)
}

