# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

curvature_kernel <- function(padded, pad, nrow_out, ncol_out, xres, yres, type, threads) {
    .Call(`_rvtr_curvature_kernel`, padded, pad, nrow_out, ncol_out, xres, yres, type, threads)
}

log_kernel <- function(padded, pad, nrow_out, ncol_out, gauss, threads) {
    .Call(`_rvtr_log_kernel`, padded, pad, nrow_out, ncol_out, gauss, threads)
}

daylight_kernel <- function(padded, pad, nrow_out, ncol_out, xres, yres, tile_x0, tile_y0, aux_mats, aux_fac, aux_cx0, aux_cy0, off_dx, off_dy, off_dist, off_start, off_end, sun_azimuth, sun_altitude, threads) {
    .Call(`_rvtr_daylight_kernel`, padded, pad, nrow_out, ncol_out, xres, yres, tile_x0, tile_y0, aux_mats, aux_fac, aux_cx0, aux_cy0, off_dx, off_dy, off_dist, off_start, off_end, sun_azimuth, sun_altitude, threads)
}

geomorphons_kernel <- function(padded, pad, nrow_out, ncol_out, dx, dy, dist, dir_start, dir_end, flat_threshold, flat_distance, threads) {
    .Call(`_rvtr_geomorphons_kernel`, padded, pad, nrow_out, ncol_out, dx, dy, dist, dir_start, dir_end, flat_threshold, flat_distance, threads)
}

horizon_svf_opns <- function(padded, pad, nrow_out, ncol_out, dx, dy, dist, dir_start, dir_end, want_svf, want_opns, want_asvf, dir_weight, threads) {
    .Call(`_rvtr_horizon_svf_opns`, padded, pad, nrow_out, ncol_out, dx, dy, dist, dir_start, dir_end, want_svf, want_opns, want_asvf, dir_weight, threads)
}

slope_hillshade <- function(padded, pad, nrow_out, ncol_out, xres, yres, sun_azimuths, sun_elevations, threads) {
    .Call(`_rvtr_slope_hillshade`, padded, pad, nrow_out, ncol_out, xres, yres, sun_azimuths, sun_elevations, threads)
}

horizon_pyramid <- function(padded, pad, nrow_out, ncol_out, tile_x0, tile_y0, aux_mats, aux_fac, aux_cx0, aux_cy0, off_dx, off_dy, off_dist, off_start, off_end, want_svf, want_opns, want_asvf, dir_weight, threads) {
    .Call(`_rvtr_horizon_pyramid`, padded, pad, nrow_out, ncol_out, tile_x0, tile_y0, aux_mats, aux_fac, aux_cx0, aux_cy0, off_dx, off_dy, off_dist, off_start, off_end, want_svf, want_opns, want_asvf, dir_weight, threads)
}

insolation_kernel <- function(padded, pad, nrow_out, ncol_out, xres, yres, tile_x0, tile_y0, aux_mats, aux_fac, aux_cx0, aux_cy0, off_dx, off_dy, off_dist, off_start, off_end, sun_azimuth, sun_altitude, air_mass0, extraterrestrial, dir_azimuth, linke, diffuse_sum, overcast, threads) {
    .Call(`_rvtr_insolation_kernel`, padded, pad, nrow_out, ncol_out, xres, yres, tile_x0, tile_y0, aux_mats, aux_fac, aux_cx0, aux_cy0, off_dx, off_dy, off_dist, off_start, off_end, sun_azimuth, sun_altitude, air_mass0, extraterrestrial, dir_azimuth, linke, diffuse_sum, overcast, threads)
}

local_dominance_kernel <- function(padded, pad, nrow_out, ncol_out, dx, dy, dist, weight, observer_height, threads) {
    .Call(`_rvtr_local_dominance_kernel`, padded, pad, nrow_out, ncol_out, dx, dy, dist, weight, observer_height, threads)
}

msrm_kernel <- function(padded, pad, nrow_out, ncol_out, radii, threads) {
    .Call(`_rvtr_msrm_kernel`, padded, pad, nrow_out, ncol_out, radii, threads)
}

max_deviation_kernel <- function(padded, pad, nrow_out, ncol_out, r_min, r_max, r_step, threads) {
    .Call(`_rvtr_max_deviation_kernel`, padded, pad, nrow_out, ncol_out, r_min, r_max, r_step, threads)
}

sky_illumination_kernel <- function(padded, pad, nrow_out, ncol_out, xres, yres, tile_x0, tile_y0, aux_mats, aux_fac, aux_cx0, aux_cy0, off_dx, off_dy, off_dist, off_start, off_end, dir_azimuth, overcast, threads) {
    .Call(`_rvtr_sky_illumination_kernel`, padded, pad, nrow_out, ncol_out, xres, yres, tile_x0, tile_y0, aux_mats, aux_fac, aux_cx0, aux_cy0, off_dx, off_dy, off_dist, off_start, off_end, dir_azimuth, overcast, threads)
}

